# Generated by Django 2.2.17 on 2021-03-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_details', models.FileField(blank=True, null=True, upload_to='tmp/')),
                ('blob_details', models.BinaryField(blank=True, editable=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
