# Generated by Django 2.2.17 on 2021-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disorder_detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='file_details',
            field=models.FileField(upload_to='tmp/'),
        ),
    ]
