# Generated by Django 2.2.17 on 2021-02-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio_player')),
            ],
        ),
    ]
