# Generated by Django 2.2.17 on 2021-03-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.TextField()),
                ('audio_file', models.FileField(upload_to='my_audios/')),
            ],
        ),
    ]
