# Generated by Django 2.2.17 on 2021-02-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(upload_to='audio_player/'),
        ),
    ]
