# Generated by Django 2.2.17 on 2021-02-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0002_auto_20210221_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='audio_file',
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio_name',
            field=models.TextField(),
        ),
    ]
