# Generated by Django 2.2.17 on 2021-02-21 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0004_audiofile_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='image_name',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='my_audios/'),
            preserve_default=False,
        ),
    ]
